apiVersion: v1
kind: Pod
metadata:
  name: dewa
  labels:
    app: salaar
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    configMap:
      name: dewa-html

---
apiVersion: v1
kind: Pod
metadata:
  name: vardha
  labels:
    app: salaar
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    configMap:
      name: vardha-html

---
apiVersion: v1
kind: Pod
metadata:
  name: naarang
  labels:
    app: salaar
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    configMap:
      name: naarang-html
