apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: cHZ0ZXN0c3RvcmFnZQ==
  azurestorageaccountkey: Q2xYcFlwN0I4UWkweXpNSVo4am1aVytFUGhHb21hd0xNN3dDbkxnUDZma2RrdVBDOHMrZFc5WStxQ0VkSXBCWGxSREh0T0RKblljQytBU3QrR3lBUmc9PQ==
