apiVersion: v1
kind: Pod
metadata:
  name: nginx-firefox-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: firefox
      image: jlesage/firefox  # A Linux-based Firefox GUI image
      env:
        - name: DISPLAY
          value: ":0"  # For GUI display (see note below)
      ports:
        - containerPort: 5800  # Web-based VNC GUI
