apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefileshare
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: myfileshare
    readOnly: false
    secretNamespace: default
