apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: default
type: Opaque
data:
  azurestorageaccountname: rajajistorageaccount      # base64 of 'mystorageaccount'
  azurestorageaccountkey: your-key # base64 of your_storage_account_key

# to change into base64
# echo -n 'mystorageaccount' | base64  
# echo -n 'your_storage_account_key' | base64  