apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: azurefileshare-volume
  volumes:
    - name: azurefileshare-volume
      persistentVolumeClaim:
        claimName: pvc-azurefileshare
